Simple branch
BaseWebDev/HT_1 pull request #1
Opened 2018-04-05 12:46 UTC by SermusAnton

Implemented parsing addition, subtraction, multiplication, division. Data entry. Cleared the code.

2018-04-06 19:54 UTC, ilpoli requested changes

2018-04-06 19:54 UTC, ilpoli commented on HT_1/Program.cs
>              Match endNumber = Regex.Match(inPhrase, @"^(\d+)$", RegexOptions.IgnoreCase);  //Если это последнее число в строке
На самом деле regex это очень сложная операция. Весь парсер, что писал на занятие, был в 100 раз быстрее, чем выполнение одной такой операции, и если действительно скорость разработки стоит выше скорости выполнения программы и простоте поддержке (regex сложно читать и поддерживать), только тогда имеет смысл использовать , regex.

2018-04-06 19:54 UTC, ilpoli commented on HT_1/Program.cs
> +                    return Convert.ToInt32(selection.Groups[1].Value) + SimpleParse(inPhrase.Substring(selection.Groups[0].Value.Length));
вынести selection.Groups[\d+].Value в отдельные переменные с ясными названиями, совершенно не читаемо что значит 0, 1 и 2.

2018-04-06 19:54 UTC, ilpoli commented on HT_1/Program.cs
> +            string pattern = @"(\-*\d+)([\*\/])(\-*\d+)";
тут используется ```@"(\-*\d+)([\*\/])(\-*\d+)"``` а выше ```@"(\-*\d+)([\+\-\*\/])"``` так и должно быть? Может вынести получения числа в отдельным метод?

2018-04-06 19:54 UTC, ilpoli commented on HT_1/Program.cs
> +                default:
не стоит так делать, тебе нужен case для деления и умножения, а если не нашел ни подходящей операции надо бросать ошибку. В любой непонятной ситуации надо бросать ошибку, программа не должна путать пользователя, если у нее что то не получается это надо сообщить и прекратить выполнение, иначе можно ввести пользователя в залужение. Например, если напишу 2^2, то получу не 4 как можно было ожидать (^ операция возведения в степень), а 1.

2018-04-09 12:19 UTC, SermusAnton commented on HT_1/Program.cs
>              Match endNumber = Regex.Match(inPhrase, @"^(\d+)$", RegexOptions.IgnoreCase);  //Если это последнее число в строке
Исправил и добавил факториал

2018-04-10 04:40 UTC, ilpoli approved these changes

2018-04-10 05:30 UTC, merged