Oop
BaseWebDev/HT_1 pull request #2
Opened 2018-04-14 19:45 UTC by SermusAnton

Redesigned in accordance with the object-oriented approach

2018-04-15 05:47 UTC, ilpoli requested changes

2018-04-15 05:47 UTC, ilpoli commented on HT_1/SimpleParser.cs
> +        public int CurIndex { get { return curIndex; } }
Можно не писать отдельно поле curIndex а написать, так public int CurIndex { get; private set; }

2018-04-15 05:47 UTC, ilpoli commented on HT_1/SimpleParser.cs
> +            mesError = String.Empty;
лучше Phrase = String.Empty, так как вызывается тот же код.

2018-04-15 05:47 UTC, ilpoli commented on HT_1/SimpleParser.cs
> +            mesError = String.Empty;
Смотри выше.

2018-04-15 05:47 UTC, ilpoli commented on HT_1/SimpleParser.cs
> +            return Try();
Phrase  = inPhrase
очень много повторения кода.

2018-04-15 05:47 UTC, ilpoli commented on HT_1/SimpleParser.cs
> +        public static int Num(string s, ref int i) {
Полагаю что этот метод и вероятно все остальные в этом классе должны быть private, это внутренние поведение класса.

2018-04-15 05:47 UTC, ilpoli commented on SimpleParser.cs
> +public class Class1
Удалить?

2018-04-15 05:47 UTC, ilpoli commented on HT_1/SimpleParserTime.cs
> +        public void Add(string inPhrase) {
Полагаю это не добавление, а установка. Разница в том что в случае добавления предполагается что добавить можно больше одного, в твоем случае только одно значение, предлагаю переименовать в Set

2018-04-15 05:47 UTC, ilpoli commented on HT_1/SimpleParser.cs
> +        public static int Parse(string s, ref int index,ref string mesError) {
Если убрать static, то и параметры передавать не надо будет index\mesError ими можно будет и так пользоваться. В этом и суть инкапсуляции.

2018-04-16 11:23 UTC, SermusAnton commented on HT_1/SimpleParserTime.cs
> +        public void Add(string inPhrase) {
Поправил, кроме свойств. Это будет большой ошибкой?

2018-04-27 05:12 UTC, ilpoli requested changes

2018-04-27 05:12 UTC, ilpoli commented on HT_1/NotParseException.cs
> +        protected NotParseException(
А зачем тут столько конструкторов?

2018-04-27 05:12 UTC, ilpoli commented on HT_1/Program.cs
> +                    ShowError(ex.Message, ex.Phrase, ex.CurIndex);
Сделай Message более умным, пусть он возвращает уже правильный текст ошибки, вместо передачи 3 отдельных параметров.

2018-04-27 12:37 UTC, SermusAnton commented
Поправил

2018-05-11 10:22 UTC, SermusAnton commented
Исправил.
Использую именно как Add
foreach (string phrase in phrases) {
             parserTimeTests.Add(phrase);
}

2018-06-06 11:08 UTC, ilpoli approved these changes

2018-06-06 13:52 UTC, merged