Add History
BaseWebDev/HT_1 pull request #3
Opened 2018-05-22 18:53 UTC by SermusAnton

2018-05-23 07:55 UTC, ilpoli requested changes

2018-05-23 07:55 UTC, ilpoli commented on HT_1/historyParser.json
> +{
Что этот файл в репозитории делает?

2018-05-23 07:55 UTC, ilpoli commented on HT_1/Program.cs
> +            File.AppendAllText(fileName, json);
ты его потом так обратно не распарсишь, надо все считать десерилизовать, добавить новый item и серилизовать и сохранить обратно.

2018-05-23 07:55 UTC, ilpoli commented on HT_1/ParserEventArgs.cs
> +        public int Operand2 { get; set; }
так просто строчку с выражением которое ввел пользователь

2018-05-23 07:55 UTC, ilpoli commented on HT_1/SimpleParser.cs
> +            if (OnCompleted != null) {
Очень хорошая идея!

2018-05-25 11:41 UTC, SermusAnton commented
Исправил

2018-06-10 06:50 UTC, ilpoli approved these changes

2018-06-13 05:52 UTC, merged